name: tubonge
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  auth_button_kit: ^1.1.6
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.2
  cloud_functions: ^5.3.2
  collection: ^1.19.0
  dartz: ^0.10.1
  email_validator: ^3.0.0
  file_picker: ^9.0.0
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  firebase_storage: ^12.4.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.7.2
  google_sign_in: ^6.2.2
  intl: ^0.20.2
  logger: ^2.5.0
  permission_handler: ^11.3.1
  scroll_to_index: ^3.0.1
  grouped_list: ^6.0.0

dev_dependencies:
  custom_lint: ^0.7.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true
